[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "cd backend && npm ci",
  "npm ci"
]

[phases.build]
cmds = [
  "bash railway-build.sh"
]

[start]
cmd = "cd backend && npm start"

