[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "cd backend && npm ci",
  "npm ci"
]

[phases.build]
cmds = [
  "cd backend && node use-postgresql.js && npm run build && npx prisma generate",
  "npm run build"
]

[start]
cmd = "cd backend && npm start"

